2019-12-03 15:01:17.207 [error] <0.595.0>@Elixir.GenAMQP.Conn:init:51 CRASH REPORT Process <0.595.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.GenAMQP.Conn':init/1 line 51
2019-12-03 15:01:17.207 [error] <0.594.0>@Elixir.GenAMQP.Conn:init:51 Supervisor 'Elixir.StaticConnSup' had child 'Elixir.ConnHub' started with 'Elixir.GenAMQP.Conn':start_link(<<"amqp://guest:guest@localhost">>, 'Elixir.ConnHub') at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.GenAMQP.Conn':init/1 line 51 in context start_error
2019-12-03 15:09:50.484 [error] <0.335.0> CRASH REPORT Process <0.335.0> with 0 neighbours exited with reason: {{already_started,<0.316.0>},{'Elixir.TestApp',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-03 15:10:23.454 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 0 neighbours exited with reason: {{already_started,<0.250.0>},{'Elixir.TestApp',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-03 15:10:52.440 [error] <0.278.0> CRASH REPORT Process <0.278.0> with 0 neighbours exited with reason: {{already_started,<0.259.0>},{'Elixir.TestApp',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-03 15:13:43.534 [error] <0.278.0> CRASH REPORT Process <0.278.0> with 0 neighbours exited with reason: {{already_started,<0.259.0>},{'Elixir.TestApp',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-03 15:15:29.307 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {{already_started,<0.271.0>},{'Elixir.TestApp',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-03 16:08:40.382 [error] <0.650.0> CRASH REPORT Process <0.650.0> with 0 neighbours exited with reason: {{already_started,<0.631.0>},{'Elixir.TestApp',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-03 16:11:29.878 [error] <0.650.0> CRASH REPORT Process <0.650.0> with 0 neighbours exited with reason: {{already_started,<0.631.0>},{'Elixir.TestApp',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-03 16:17:08.088 [error] <0.288.0> Supervisor 'Elixir.AppSupervisor' had child 'Elixir.StaticConnSup' started with 'Elixir.GenAMQP.ConnSupervisor':start_link('Elixir.StaticConnSup', [{'Elixir.ConnHub',<<"amqp://guest:guest@localhost">>}]) at undefined exit with reason {already_started,<0.268.0>} in context start_error
2019-12-03 16:20:47.620 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :strategy option to be given">>} in 'Elixir.Supervisor':init/2 line 609 in application_master:init/4 line 138
2019-12-03 16:39:45.501 [error] <0.329.0> gen_server 'Elixir.TestServers.NothingServer_meck' terminated with reason: killed
2019-12-03 16:39:45.507 [error] <0.329.0> CRASH REPORT Process 'Elixir.TestServers.NothingServer_meck' with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 432
